-- FLEET SAFETY & COMPLIANCE DATA WAREHOUSE 


CREATE OR REPLACE WAREHOUSE BI_WH
WITH WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;


-- STEP 1: Create database and schema
CREATE OR REPLACE DATABASE FLEET_COMPLIANCE_DB;
USE DATABASE FLEET_COMPLIANCE_DB;
CREATE OR REPLACE SCHEMA MARITIME_REPORTING;



-- STEP 2: Create tables

-- INCIDENT REPORTS TABLE
CREATE OR REPLACE TABLE MARITIME_REPORTING.INCIDENT_REPORTS (
    INCIDENT_ID INT AUTOINCREMENT PRIMARY KEY,
    INCIDENT_TYPE STRING,
    SHIP_NAME STRING,
    REPORTED_DATE DATE,
    RESOLVED_DATE DATE,
    SEVERITY_LEVEL STRING,
    REPORTED_BY_TEAM STRING,
    STATUS STRING
);

-- SHIP VISIT LOGS TABLE
CREATE OR REPLACE TABLE MARITIME_REPORTING.SHIP_VISIT_LOGS (
    VISIT_ID INT AUTOINCREMENT PRIMARY KEY,
    SHIP_NAME STRING,
    VISIT_DATE DATE,
    VISITOR_NAME STRING,
    VISIT_OUTCOME STRING,
    BBSC_NOTES STRING
);

-- COMPLIANCE SCORES TABLE
CREATE OR REPLACE TABLE MARITIME_REPORTING.COMPLIANCE_SCORES (
    SCORE_ID INT AUTOINCREMENT PRIMARY KEY,
    SHIP_NAME STRING,
    COMPLIANCE_TYPE STRING,
    SCORE_DATE DATE,
    SCORE_VALUE DECIMAL(5,2),
    THRESHOLD_PASSED BOOLEAN
);

-- TRAINING RECORDS TABLE
CREATE OR REPLACE TABLE MARITIME_REPORTING.TRAINING_RECORDS (
    EMPLOYEE_ID INT,
    ROLE STRING,
    TRAINING_TYPE STRING,
    COMPLETION_DATE DATE,
    IS_MANDATORY BOOLEAN
);


