
--- Applying Masking Policy

CREATE ROLE IF NOT EXISTS FULL_ACCESS_ROLE;
CREATE ROLE IF NOT EXISTS ANALYST_ROLE;

-- Create a new masking policy for Visitor Name
CREATE OR REPLACE MASKING POLICY MASK_VISITOR_NAME
AS (val STRING)
RETURNS STRING ->
CASE
  WHEN CURRENT_ROLE() IN ('FULL_ACCESS_ROLE') THEN val
  ELSE '***MASKED***'
END;

-- Apply it to a column
ALTER TABLE MARITIME_REPORTING.SHIP_VISIT_LOGS
MODIFY COLUMN VISITOR_NAME 
SET MASKING POLICY MASK_VISITOR_NAME;



GRANT ROLE FULL_ACCESS_ROLE TO USER Deepak;
GRANT ROLE ANALYST_ROLE TO USER Deepak;


-- Switch to role with full access
USE ROLE FULL_ACCESS_ROLE;
Use ROLE ANALYST_ROLE;
-- Should show real names
SELECT VISIT_ID, SHIP_NAME, VISITOR_NAME
FROM MARITIME_REPORTING.SHIP_VISIT_LOGS
LIMIT 5;

